sudo: required
os:
- linux
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
cache:
- apt: true
- directories:
  - "$HOME/.npm"
  - "$HOME/.electron"
  - node_modules
before_script:
  - npm install -g gulp
  - gulp clean
script: 
  - gulp coverage
  - cat ./coverage/lcov.info | codecov
  - gulp pack
after_success:
  - cd dist
  - ls -la
  - cd made-linux-*
  - ls -la
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
deploy:
  provider: releases
  api_key: "${togh_key}"
  file: README.md
  skip_cleanup: true
  on:
    tags: true