sudo: required
os:
- linux
- win32
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
cache:
- apt: true
- directories:
  - "$HOME/.npm"
  - "$HOME/.electron"
before_script:
  - npm install -g gulp
script: 
  - gulp test
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/