sudo: required
os:
- linux
language: node_js
node_js:
- '6'
cache:
- apt: true
- directories:
  - "$HOME/.npm"
  - "$HOME/.electron"
  - node_modules
# before_install:
#   - sudo apt-get -qq update
#   - sudo apt-get install wine
before_script:
  - npm install -g gulp
  - gulp clean
script: 
  - gulp coverage
  - cat ./coverage/lcov.info | codecov
  - gulp pack
  # - gulp pack --platform win32
after_success:
  - ls -la
  - cd dist
  - ls -la
  - cd ..
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
deploy:
  provider: releases
  api_key: "${togh_key}"
  file: "./dist/made-0.0.1-linux-x64.zip"
  # - "./dist/made-v0.0.1-win32-x64.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true