sudo: required
os:
- linux
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
cache:
- apt: true
- directories:
  - "$HOME/.npm"
  - "$HOME/.electron"
before_script:
  - npm install -g gulp
  - gulp clean
script: 
  - gulp coverage
  - cat ./coverage/lcov.info | codecov
after_success:
  - echo "success"
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/