environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulp

test_script:
  - node --version
  - npm --version
  - gulp clean
  - gulp pack --platform win32
  - cd dist
  - dir
  - cd ..
  - dir

build: off

artifacts:
  - path: '\dist\made-*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: sNM501oS+WDpQmybbdIeswkmKS1NxnbNhtf+ntQkng944ZsxxFBb2pabxkN6/VX3   
  draft: false
  prerelease: false
  on:
    branch: /^v\d+\.\d+\.\d+/
    appveyor_repo_tag: true

after_deploy: